name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout Foo
      uses: actions/checkout@v2
      with:
        path: foo

    - name: Checkout Bar
      uses: actions/checkout@v2
      with:
        repository: smbache/bar
        path: bar

    - name: where am i
      run: |
        pwd

    - name: what is here
      run: |
        ls -R
